### PR TITLE
Tutorial: Chemistry Example 1

### PR DESCRIPTION
**Pull request by rrbuchholz**
Adding in the chemistry example 1 to the Jupyter Notebooks.

### CODE REVIEW

**Comment by rrbuchholz** [comment]
Added the start of exercise 2 to my fork - it automatically added to this pull request. I harmonized my fork with NCAR's repo today as well.

**Comment by cecilehannay** [comment]
I will review your 2 exercises.

**Comment by cecilehannay** [comment]
[rrbuchholz](https://github.com/rrbuchholz): I am having problems with your notebook `cam-chem_waccm.ipynb` that is not in a notebook format. I tried to merge to see if I can fix it but I am having issues. Is it working on your side? Are you able to open it on the JupyterHub? Could you check? Thanks.

**Comment by rrbuchholz** [comment]
I think I fixed the cam-chem_waccm.ipynb, see here: https://github.com/NCAR/CESM-Tutorial/pull/95

**Pull request merged**
